<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Notebook;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Notebook-related functionality
 */
class NotebookController extends Controller
{
    /**
     * Add Notebook entry
     */
    public function add(Request $request)
    {
        // Add optional data (if missing) not to get an error on entity creation
        $request->mergeIfMissing(['birthday' => null]);
        $request->mergeIfMissing(['company' => null]);
        $request->mergeIfMissing(['id' => Str::orderedUuid()->toString()]);

        // Validate client input
        // If client sent wrong data, adequate response is being generated by Laravel
        $validatedData = $request->validate([
            'id' => 'required|uuid|unique:notebooks',
            'name' => 'required|string|max:255',
            'company' => 'nullable|string|max:255',
            'phone' => 'required|string|min:10|max:18',
            'email' => 'required|email:rfc,dns|unique:notebooks',
            // Use date format YYYY-MM-DD
            'birthday' => 'nullable|date_format:Y-m-d',
            'picture' => 'nullable|mimes:jpeg,jpg,png,gif,svg',
        ]);

        // Save file, if present
        $picPath = null;
        if ($request->hasFile('picture')) {
            $folderPath = 'images/' . date("Y") . '/' . date("m");
            $picPath = $validatedData['picture']->store($folderPath, 'public');
        }

        // Create new Notebook entry
        Notebook::create([
            'id' => $validatedData['id'],
            'creator_uuid' => Auth::user()->id,
            'name' => $validatedData['name'],
            'company' => $validatedData['company'],
            'phone' => $validatedData['phone'],
            'email' => $validatedData['email'],
            'birthday' => $validatedData['birthday'],
            'picture' => $picPath,
        ]);

        return response()->json([
            'message' => 'Entry added.',
        ], 201);
    }
}
